int _putchar(char c);
void _puts_recursion(char *str);
void _print_rev_recursion(char *str);
int _strlen_recursion(char *str);
int factorial(int a);
int _pow_recursion(int num, int pow);
int validator(int, int);
int _sqrt_recursion(int);
int prime(int, int);
int is_prime_number(int n);
int is_palindrome(char *s);
int wildcmp(char *s1, char *s2);
